artgest/urls.py
#  artgest/urls.py


from . import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static


app_name = "artgest"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('sobre', views.sobre_page_view, name='sobre'),
    path('info', views.info_page_view, name='info'),
    path('userpage', views.userpage_page_view, name='userpage'),
    path('produtos_registar', views.registar_produtos_page_view, name='produtos_registar'),
    path('guardar_produto/<int:tipoprod_codigo>/<str:preco>', views.guardar_produto_view, name='guardar_produto'),
    path('produtos_listar', views.listar_produtos_page_view, name='produtos_listar'),
    path('produtos_editar/<int:tipoprod_codigo>', views.editar_produtos_page_view, name='produtos_editar'),
    path('produtos_eliminar/<int:tipoprod_codigo>', views.eliminar_produtos_page_view, name='produtos_eliminar'),
    path('produtos_visualizar/<int:tipoprod_codigo>', views.visualizar_produtos_page_view, name='produtos_visualizar'),
    path('producao_eliminar/<int:tipoprod_codigo>', views.eliminar_producao_view, name='producao_eliminar'),
    path('materiasprimas_registar', views.registar_materiasprimas_page_view, name='materiasprimas_registar'),
    path('materiasprimas_listar', views.listar_materiasprimas_page_view, name='materiasprimas_listar'),
    path('materiasprimas_editar/<int:materia_prima_codigo>', views.editar_materiasprimas_page_view, name='materiasprimas_editar'),
    path('materiasprimas_eliminar/<int:materia_prima_codigo>', views.eliminar_materiasprimas_view, name='materiasprimas_eliminar'),
    path('gastos_registar', views.registar_gastos_page_view, name='gastos_registar'),
    path('gastos_listar', views.listar_gastos_page_view, name='gastos_listar'),
    path('gastos_editar/<int:gasto_codigo>', views.editar_gastos_page_view, name='gastos_editar'),
    path('gastos_eliminar/<int:gasto_codigo>', views.eliminar_gastos_view, name='gastos_eliminar'),
    path('fornecedores_registar', views.registar_fornecedores_page_view, name='fornecedores_registar'),
    path('fornecedores_listar', views.listar_fornecedores_page_view, name='fornecedores_listar'),
    path('fornecedores_editar/<str:fornecedor_nipc>', views.editar_fornecedores_page_view, name='fornecedores_editar'),
    path('fornecedores_eliminar/<str:fornecedor_nipc>', views.eliminar_fornecedores_view, name='fornecedores_eliminar'),
    path('instrucoes_registar', views.registar_instrucoes_page_view, name='instrucoes_registar'),
    path('instrucoes_listar', views.listar_instrucoes_page_view, name='instrucoes_listar'),
    path('instrucoes_editar/<int:instrucao_codigo>', views.editar_instrucoes_page_view, name='instrucoes_editar'),
    path('instrucoes_eliminar/<int:instrucao_codigo>', views.eliminar_instrucoes_view, name='instrucoes_eliminar'),
    path('prodvendidos_registar', views.registar_prodvendidos_page_view, name='prodvendidos_registar'),
    path('prodvendidos_listar', views.listar_prodvendidos_page_view, name='prodvendidos_listar'),
    path('prodvendidos_editar/<int:pv_codigo_venda>', views.editar_prodvendidos_page_view, name='prodvendidos_editar'),
    path('prodvendidos_eliminar/<int:pv_codigo_venda>', views.eliminar_prodvendidos_view, name='prodvendidos_eliminar'),
    path('relatorios', views.relatorios_page_view, name='relatorios'),
    path('alertas', views.alertas_page_view, name='alertas'),
    path('limpa_alerta/<int:alerta_codigo>', views.limpa_alerta_page_view, name='limpa_alerta'),
    path('perfil/<int:artesao_codigo>', views.perfil_page_view, name='perfil'),
    path('perfil_visualizar/<int:artesao_codigo>', views.perfil_visualizar_page_view, name='perfil_visualizar'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artgest.urls')),
]

artgest/views.py
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.db import connection

from artgest.forms import ProducaoForm, MateriaPrimaForm, TipoProdForm, GastosForm, FornecedorForm, InstrucoesForm, \
    ProdVendidoForm, GastosProdForm, MpProdForm, ArtesaoForm
from artgest.models import Producao, MateriaPrima, Gastos, Fornecedor, Instrucoes, ProdVendido, TipoProd, GastosProd, \
    Alerta, Artesao, MpProd


# faz uma verificação de autenticação e redireciona para a página de utilizador (userpage.html) se autenticado
# ou a página inícial (home.html) se não autenticado
def home_page_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:userpage'))

    registar_form = ArtesaoForm(request.POST or None)

    if registar_form.is_valid():
        registar_form.save()
        messages.success(request, 'Utilizador registado com êxito! Já poderá efetuar o Login.', extra_tags='Sucesso')
        return HttpResponseRedirect(reverse('artgest:home'))
    elif request.method == 'POST' and not registar_form.is_valid():
        print(messages.error())
        messages.error()

    context = {
        'titulo': 'Home',
        'registar_form': registar_form,

    }

    return render(request, 'artgest/home.html', context)


# Recebe dados de autenticação através de um método POST e chama o método de autenticação do Django
# Reireciona para a página de utilizador (userpage.html) se autenticado
# ou para a página inícial (home.html) se não autenticado
def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('artgest:userpage'))

    return HttpResponseRedirect(reverse('artgest:home'))


# Chama o método logout() do Django e redireciona para a página inicial (home.html)
def logout_view(request):
    logout(request)

    return HttpResponseRedirect(reverse('artgest:home'))


# Retorna a página sobre (sobre.html).
def sobre_page_view(request):
    context = {
        'titulo': 'Sobre Nós'
    }

    return render(request, 'artgest/sobre.html', context)


# Retorna a página informações (info.html)
def info_page_view(request):
    context = {
        'titulo': 'Informações'
    }

    return render(request, 'artgest/info.html', context)


# faz uma verificação de autenticação e redireciona para a página de utilizador (userpage.html) se autenticado
# ou a página inícial (home.html) se não autenticado
def userpage_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:home'))

    context = {
        'titulo': 'Userpage',
        'artesao_codigo': request.user.codigo
    }

    return render(request, 'artgest/userpage.html', context)


# faz uma verificação de autenticação e redireciona para a página inícial (home.html) se não autenticado
# se autenticado, cria um form de tipo de produto e redireciona para a página de registar produtos (produtos_registar.html)
def registar_produtos_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:home'))

    tprod_form = TipoProdForm(request.POST, request.FILES)

    if tprod_form.is_valid():

        with connection.cursor() as cursor:
            cursor.execute("SELECT TIPO_PROD_COD_SEQ.NEXTVAL FROM DUAL;")
            nextval = cursor.fetchone()
        tipoprod_codigo = nextval[0]
        cursor.close()
        instancia = tprod_form.save(commit=False)
        instancia.codigo = tipoprod_codigo
        instancia.save()
        return redirect('artgest:produtos_visualizar', tipoprod_codigo)

    elif request.method == 'POST' and not tprod_form.is_valid():
        messages.error(request,
                       'Não é possível avançar. '
                       'Verifique se o tipo de produto já existe ou se tem os campos corretamente preenchidos.',
                       extra_tags='Atenção')

    context = {
        'titulo': 'Registar Tipo de Produto',
        'tprod_form': tprod_form,
        'artesao_codigo': request.user.codigo

    }

    return render(request, 'artgest/produtos_registar.html', context)


# finaliza o registo de tipos de produtos
def guardar_produto_view(request, tipoprod_codigo, preco):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:home'))

    tipoproduto = TipoProd.objects.get(codigo=tipoprod_codigo)

    tipoproduto.preco = preco
    tipoproduto.save()

    tiposproduto = TipoProd.objects.all().order_by('-codigo')

    colunas = ['Código', 'Nome', 'Custo de Produção', 'Lucro', 'Preço Unidade', 'Categoria']

    context = {
        'titulo': 'Tipos de Produto',
        'tiposproduto': tiposproduto,
        'colunas': colunas,
        'artesao_codigo': request.user.codigo
    }

    return render(request, 'artgest/produtos_listar.html', context)


# faz uma verificação de autenticação e redireciona para a página inícial (home.html) se não autenticado
# se autenticado, cria forms de Producao, Matérias-Primas e Gastos, e redireciona para a página de visualizar produtos (produtos_visualizar.html)
def visualizar_produtos_page_view(request, tipoprod_codigo):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:home'))

    user_codigo = request.user.codigo
    email = request.user.email
    preco_ideal = None
    mpprod_existe = False
    gastosprod_existe = False

    try:
        producao = Producao.objects.get(artesao_codigo=user_codigo, tipo_prod_codigo=tipoprod_codigo)
        print('produto seleccionado')
        preco_ideal = calcula_preco_ideal_view(email, producao.id)[0].get('PRECO_IDEAL')
    except:
        producao = None

    try:
        mpprod = MpProd.objects.filter(id=producao.id).values()
        mpprod_existe = mpprod.exists()
        print('materias primas seleccionadas')
    except:
        mpprod = None

    try:
        gastosprod = GastosProd.objects.filter(id=producao.id).values()
        gastosprod_existe = gastosprod.exists()
        print('gasto seleccionado')
    except:
        gastosprod = None

    tipoproduto = TipoProd.objects.get(codigo=tipoprod_codigo)
    tprod_form = TipoProdForm(instance=tipoproduto)
    producao_form = ProducaoForm(request.POST or None)
    mpprod_form = MpProdForm(request.POST or None)
    gastosprod_form = GastosProdForm(request.POST or None)

    if 'inserir-producao-bd' in request.POST and producao_form.is_valid():
        producao_form.save()
        producao_form = ProducaoForm()
        messages.success(request, 'A Produção foi acrescentada ao Tipo de Produto.', extra_tags='Sucesso')
        return HttpResponseRedirect(reverse_lazy('artgest:produtos_visualizar', args=[tipoprod_codigo]))

    if 'inserir-mpprod-bd' in request.POST:
        mpprod_form.save()
        mpprod_form = MpProdForm()
        messages.success(request, 'A matéria-prima foi acrescentada ao Tipo de Produto.', extra_tags='Sucesso')
        return HttpResponseRedirect(reverse_lazy('artgest:produtos_visualizar', args=[tipoprod_codigo]))

    if 'inserir-gasto-bd' in request.POST:
        gastosprod_form.save()
        gastosprod_form = GastosProdForm()
        messages.success(request, 'O Gasto foi acrescentado ao Tipo de Produto.', extra_tags='Sucesso')
        return HttpResponseRedirect(reverse_lazy('artgest:produtos_visualizar', args=[tipoprod_codigo]))

    context = {
        'titulo': 'Finalizar Registo do Tipo de Produto',
        'tipoproduto': tipoproduto,
        'tprod_form': tprod_form,
        'producao': producao,
        'preco_ideal': preco_ideal,
        'mpprod': mpprod,
        'mpprod_existe': mpprod_existe,
        'gastosprod': gastosprod,
        'gastosprod_existe': gastosprod_existe,
        'producao_form': producao_form,
        'mpprod_form': mpprod_form,
        'gastosprod_form': gastosprod_form,
        'user_codigo': user_codigo,
        'artesao_codigo': request.user.codigo
    }

    return render(request, 'artgest/produtos_visualizar.html', context)


#  calcula o preço ideal de um tipo de produto
def calcula_preco_ideal_view(email, producao_id):
    with connection.cursor() as cursor:
        try:
            cursor.execute('SELECT UTILS_PKG.PRECO_IDEAL_FNC(%s, %s) AS PRECO_IDEAL FROM DUAL', [email, producao_id])
            preco_ideal = dictfetchall(cursor)
        except:
            print('Sem resultados')
        cursor.close()

    return preco_ideal


# faz uma verificação de autenticação e redireciona para a página inícial (home.html) se não autenticado
# se autenticado, faz consulta à base de dados para obter e retornar todos os registos
def listar_produtos_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('artgest:home'))

    tiposproduto = TipoProd.objects.all().order_by('-codigo')

    colunas = ['Código', 'Nome', 'Lucro', 'Preço Unidade', 'Categoria']

    context = {
        'titulo': 'Tipos de Produto',
        'tiposproduto': tiposproduto,
        'colunas': colunas,
        'artesao_codigo': request.user.codigo
    }

    return render(request, 'artgest/produtos_listar.html', context)


# faz uma verificação de autenticação e redireciona para a página inícial (home.html) se não autenticado
# se autenticado, faz consulta à base de dados, cria um form com base no registo recebido e retorna uma página de edição
# valida o form e insere os dados na base de dados
def editar_produtos_page_view(request, tipoprod_codigo):
    if not request.user.is_authenticated:

artgest/templates/artgest/alertas.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message.extra_tags }}: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
    <hr>
    <div>
        {% for alerta in alertas %}
        <div class="clss-alerta">
            {{ alerta }}
            <a href="{% url 'artgest:limpa_alerta' alerta.codigo %}"><i class="fa fa-trash fa-lg limpa-alerta" aria-hidden="true"></i></a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

artgest/templates/artgest/fornecedores_registar.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block scripts %}
    <script src="{% static 'artgest/js/fornecedores_registar.js' %}"></script>
{% endblock %}

{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Sucesso: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
    <hr>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="clss-form-registar-mp">
            <p class="clss-obrigatorio">{{ fornecedores_form.nipc.label }}<span>&#42;</span>{{ fornecedores_form.nipc }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.nome.label }}<span>&#42;</span>{{ fornecedores_form.nome }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.email.label }}<span>&#42;</span>{{ fornecedores_form.email }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.morada.label }}<span>&#42;</span>{{ fornecedores_form.morada }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.n_porta.label }}<span>&#42;</span>{{ fornecedores_form.n_porta }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.cod_postal.label }}<span>&#42;</span>{{ fornecedores_form.cod_postal }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.localidade.label }}<span>&#42;</span>{{ fornecedores_form.localidade }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.concelho.label }}<span>&#42;</span>{{ fornecedores_form.concelho }}</p>

            <p class="clss-obrigatorio">{{ fornecedores_form.telefone.label }}<span>&#42;</span>{{ fornecedores_form.telefone }}</p>
            <br>
            <span class="clss-obrigatorio-msg">&#42; Campo de preenchimento obrigatório</span></p>

        </div>

        <br>

        <button type="button" id="bt-registar" class="btn btn-primary float-right mr-5">Registar</button>
        <a href="{% url 'artgest:fornecedores_registar' %}" role="button" class="btn btn-secondary float-right mr-1">Limpar</a>

        <div id="modal-confirmacao" class="clss-modal-fundo">
            <div class="clss-modal-confirmacao modal-fade">
                <div class="clss-modal-confirmacao-conteudo">
                    <h4><strong>Confirmar?</strong></h4>
                    <hr>
                    <p>Tem a certeza que pretende registar o fornecedor?</p>
                    <hr>
                    <div class="clss-modal-botoes">
                        <button type="button" id="bt-cancelar" class="mb-5 btn btn-secondary btn-sm">Cancelar</button>
                        <button type="submit" class="mb-5 btn btn-primary btn-sm">Sim, registar</button>
                    </div>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

artgest/templates/artgest/gastos_editar.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block scripts %}
    <script src="{% static 'artgest/js/gastos_editar.js' %}"></script>
{% endblock %}

{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Sucesso: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ gastos_form.as_p }}
            <br>
            <button type="button" id="bt-guardar" class="btn btn-primary float-right">Guardar</button>
            <a href="{% url 'artgest:gastos_listar' %}" role="button" class="btn btn-secondary float-right mr-1">Cancelar</a>

            <div id="modal-confirmacao" class="clss-modal-fundo">
                <div class="clss-modal-confirmacao modal-fade">
                    <div class="clss-modal-confirmacao-conteudo">
                        <h4><strong>Confirmar?</strong></h4>
                        <hr>
                        <p>Tem a certeza que pretende guardar as alterações efetuadas?</p>
                        <hr>
                        <div class="clss-modal-botoes">
                            <button type="button" id="bt-cancelar" class="mb-5 btn btn-secondary btn-sm mr-1">Cancelar</button>
                            <button type="submit" class="mb-5 btn btn-primary btn-sm">Sim, guardar</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
{% endblock %}

artgest/templates/artgest/gastos_listar.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block scripts %}
    <script src="{% static 'artgest/js/gastos_listar.js' %}"></script>
{% endblock %}


{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message.extra_tags }}: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
    <hr>
    <div id="tabela-materias-primas">
        <table>
            <thead>
                {% for coluna in colunas %}
                    <th>{{ coluna }}</th>
                {% endfor %}
            </thead>
            <tbody>
                {% for g in gastos  %}
                    <tr>
                        <td>{{ g.codigo }}</td>
                        <td>{{ g.nome }}</td>
                        <td>{{ g.valor }}</td>
                        <td><a href="{% url 'artgest:gastos_editar' g.codigo %}" class="btn btn-primary btn-sm" >Editar</a></td>
                        <td><button type="button" onclick='eliminar_registo("{% url 'artgest:gastos_eliminar' g.codigo %}")' class="btn btn-danger btn-sm float-right mr-1">Eliminar</button></td>
                    </tr>
                    <div id="modal-confirmacao" class="clss-modal-fundo">
                        <div class="clss-modal-confirmacao modal-fade">
                            <div class="clss-modal-confirmacao-conteudo">
                                <h4><strong>Confirmar?</strong></h4>
                                <hr>
                                <p>Tem a certeza que pretender eliminar?</p>
                                <hr>
                                <div class="clss-modal-botoes">
                                    <button type="button" id="bt-cancelar" class="mb-5 btn btn-secondary btn-sm">Cancelar</button>
                                    <a id="bt-eliminar" href="#" role="button" class="mb-5 btn btn-danger btn-sm">Sim, eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

artgest/templates/artgest/info.html
{% extends 'artgest/base.html' %}

{% block main %}
    <section class="info">

    <div class="info-top">
        <p>Através do ArtGest, poderá fazer a gestão dos seus <br>
        produtos, matérias-primas e gastos! </p>
    </div>

        <div class="container">

            <div class="row justify-content-md-center">
                <div class="col-md-3 box box-info">
                    <h3>Produção</h3>
                    <p>
                        Obtenha o preço ideal para o seu produto, faça a gestão do seu estoque e crie alertas para quantidade mínima de produtos desejada.
                    </p>
                </div>

                <div class="col-md-3 box box-info">
                    <h3>Matéria-prima</h3>
                    <p>
                        Faça a gestão do seu estoque, crie alertas para quantidade mínima de matérias-primas desejada e listas de compras.
                    </p>
                </div>

                <div class="col-md-3 box box-info">
                    <h3>Gastos</h3>
                    <p>
                        Faça a gestão dos seus gastos de produção.
                    </p>
                </div>

            </div>

        </div>
    </section>
{% endblock %}

artgest/templates/artgest/instrucoes_listar.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block scripts %}
    <script src="{% static 'artgest/js/instrucoes_listar.js' %}"></script>
{% endblock %}


{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Sucesso: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
    <hr>
    <div id="tabela-materias-primas">
        <table>
            <thead>
                {% for coluna in colunas %}
                    <th>{{ coluna }}</th>
                {% endfor %}
            </thead>
            <tbody>
                {% for instrucao in instrucoes  %}
                    <tr>
                        <td>{{ instrucao.nome }}</td>
                        <td>{{ instrucao.instrucao }}</td>
                        <td>{{ instrucao.imagem }}</td>
                        <td><a href="{% url 'artgest:instrucoes_editar' instrucao.codigo %}" class="btn btn-primary btn-sm" >Editar</a></td>
                        <td><button type="button" onclick='eliminar_registo("{% url 'artgest:instrucoes_eliminar' instrucao.codigo %}")'
                            class="btn btn-danger btn-sm float-right mr-1">Eliminar</button></td>
                    </tr>
                    <div id="modal-confirmacao" class="clss-modal-fundo">
                        <div class="clss-modal-confirmacao modal-fade">
                            <div class="clss-modal-confirmacao-conteudo">
                                <h4><strong>Confirmar?</strong></h4>
                                <hr>
                                <p>Tem a certeza que pretender eliminar?</p>
                                <hr>
                                <div class="clss-modal-botoes">
                                    <button type="button" id="bt-cancelar" class="mb-5 btn btn-secondary btn-sm">Cancelar</button>
                                    <a id="bt-eliminar" href="#" role="button" class="mb-5 btn btn-danger btn-sm">Sim, eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

artgest/templates/artgest/produtos_listar.html
{% extends 'artgest/base.html' %}

{% load static %}

{% block scripts %}
    <script src="{% static 'artgest/js/produtos_listar.js' %}"></script>
{% endblock %}


{% block message %}
    {#  mostra notificação se houver mensagens retornadas da view após submissão do form #}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show modal-fade" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message.extra_tags }}: </strong> {{ message }}
        </div>
    {% endfor %}
{% endblock %}

{% block main %}
    <h1>{{ titulo }}</h1>
    <hr>
    <div id="tabela-materias-primas">
        <table>
            <thead>
                {% for coluna in colunas %}
                    <th>{{ coluna }}</th>
                {% endfor %}
            </thead>
            <tbody>
                {% for tp in tiposproduto  %}
                    <tr>
                        <td>{{ tp.codigo }}</td>
                        <td>{{ tp.nome }}</td>
                        <td>{{ tp.lucro }}</td>
                        <td>{{ tp.preco }}</td>
                        <td>{{ tp.categoria_codigo }}</td>
                        <td><a href="{% url 'artgest:produtos_editar' tp.codigo %}" class="btn btn-primary btn-sm" >Editar</a></td>
                        <td><button type="button" onclick='eliminar_registo("{% url 'artgest:produtos_eliminar' tp.codigo %}")' class="btn btn-danger btn-sm float-right mr-1">Eliminar</button></td>
                    </tr>
                    <div id="modal-confirmacao" class="clss-modal-fundo">
                        <div class="clss-modal-confirmacao modal-fade">
                            <div class="clss-modal-confirmacao-conteudo">
                                <h4><strong>Confirmar?</strong></h4>
                                <hr>
                                <p>Tem a certeza que pretender eliminar?</p>
                                <hr>
                                <div class="clss-modal-botoes">
                                    <button type="button" id="bt-cancelar" class="mb-5 btn btn-secondary btn-sm">Cancelar</button>
                                    <a id="bt-eliminar" href="#" role="button" class="mb-5 btn btn-danger btn-sm">Sim, eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}